name: friflex_weather_app
description: Weather App for Friflex
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  equatable: ^2.0.3
  http: ^0.13.5
  get_it: ^7.2.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  connectivity_plus: 2.0.0
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
flutter:
  uses-material-design: true

  assets:
    - assets/conditions/